language: java
jdk:
  - oraclejdk11
script:
  - ./gradlew clean test
  - ./gradlew build

before_install:
  - chmod +x gradlew
  - export TZ=Brazil/East

deploy:
  provider: heroku
  api_token:
    secure: $HEROKU_API_KEY
  app: mf-config-server-api