server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}/eureka

spring:
  application:
    name: mf-config-server-api
  main:
    banner-mode: 'off'
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/rafabart/mf-config-server
          username: ${GITHUB_USER}
          password: ${GITHUB_PASS}
          search-paths: '{application}'